### ISSUE TITLE
A question about data processing

### ISSUE THREAD

**Issue by caoxy01** [SJTU-ViSYS/multi-instant-reg#2]
Hi,
Thank you for the excellent work! I'm having some problems runing './synthetic&real/run.sh'. It shows that FileNotFoudError: '{scan2cadroot}/split.json' and 'modelnet40_normal_resampled/modelnet40_train.json'. The  screen shot is as follows
![051284e6bb68e349af21af8061fd83d](https://user-images.githubusercontent.com/108921306/196866811-b348c3e6-1093-4ffb-a7a1-01cf3b9c85a1.png)
I will appreciate if you can give me some hint. Thank you!

**Comment by Gilgamesh666666** [comment]
I have sent those files to you through email, please check. And I also upload them and update Readme file. Sorry for the inconvenience.
